saraswati258/hacktoberfest2022

CPP/fenwick tree.cpp

i have added "fenwick tree algorithm"
please kindly accept this PR and added it to for hacktobarfest.

added fenwick Tree algorithm

---

CPP/numberOfWaysToWearDifferentHatsToEachOther.cpp

i have added "Number of way to wear different hats" dsa problem
plz kindly accept this to PR and added it to hacttobarfest.

added Number of way to wear different hats

---

CPP/quickSort.cpp

Kindly accept this PR
and add Hacktober fest tag

Added Quick sort

---

CPP/insertionSortingAlgorithm.cpp

Kindly accept this PR and add hacktoberfest accepted tag.

added insertion sorting algorithm

---

CPP/RadixSort.cpp
CPP/insertionSortingAlgorithm.cpp

Kindly accept this PR and add hacktoberfest accepted tag.

Added Radix sort

---

CPP/bfsInGraph.cpp
CPP/insertionSortingAlgorithm.cpp

Kindly accept this PR and add hacktoberfest accepted tag.

Added bfs code for graph

---

CPP/bucketSort.cpp
CPP/insertionSortingAlgorithm.cpp

Kindly accept this PR and add hacktoberfest accepted tag.

Added Bucket sort

---

CPP/boruvka_algo.cpp

Added boruvka's algo 
Kindly accept this PR and add Hacktober fest tag

Added Boruvka's Algorithm

---

CPP/segment tree with lazy propagation.cpp

i have added segment tree with lazy propagation
plz kindly accept this PR and added to for hacktobarfest.

added segment with lazy propagation

---

CPP/prim'sAlgo.cpp

I have added c++ code for Prim's Algorithm.
Please accept this PR and please add the tag of hacktoberfest accepted.

added prim's algo

---

CPP/flatBinaryTree.cpp

Added a code to flatten a binary tree in c++
Kindly accept this PR and add Hacktoberfest Tag.

Flatten a Binary Tree in C++

---

CPP/BitonicSort.cpp

I have added c++ code for Bitonic Sort.
Please accept this PR and add hacktoberfest accepted tag.

added bitonic sort

---

CPP/hierHolzer_algo.cpp

Added code for Hierholzer's algo .
Kindly accept this PR and add Hacktoberfest Tag.

HierHolzer's Algorithm

---

CPP/segment tree with lazy propagation.cpp

i have added "segmet tree to lazy propagation algorithm"
please kindly accept this PR and added it to for hacktobarfest.

added segment tree to lazy propagation algorithm:

---

CPP/reverse_list_in_K_groupp.cpp

I have added c++ code for reversing the link list in group of K.
Please accept this PR and add hacktoberfest accepted tag.

added reverse list in group of K

---

CPP/binary_search.cpp

Recursive implementation of Binary Search

Hacktoberfest2022 binary_search.cpp

---

CPP/djikstra_algo.cpp

Added Djikstra algo for CPP.
Kindly accept this PR.

Djikstra Algorithm for Graphs

---

CPP/mooreVoting.cpp

I have added **Moore's voting algorithm** in C++.
Please accept the PR and add hanckertober tag

Moore's voting algo

---

CPP/intersection-of-two-linked-lists.cpp

Given the heads of two singly linked-lists headA and headB, return the node at which the two lists intersect.

Created intersection-of-two-linked-lists.cpp

---

CPP/fibonacciSearch.cpp

I have added fibonacci search in cpp.
Please merge the PR and add hacktoberfest tag.

fibonacci search

---

CPP/pathSum

I have added a C++ code for Leetcode 112 problem path Sum.

leetcode 112 path sum

---

Python/cache clearing script/clearcache.py

Browser cache clearing python script

cache clearing script

---

CPP/lcs

I have added a C++ code for leetcode 128 problem longest consecutive sequence.

Leetcode 128 Longest Consecutive Sequence

---

CPP/unionFind

I have added a C++ code for union Find algorithm.

union find algorithm

---

CPP/isPrime.cpp
CPP/unionFind.cpp

I have added a C++ code for an algorithm to check a number is prime or not.

algorithm to check a number is prime or not

---

CPP/smallestPrimeFactorFrom1toN

I have added a C++ code for an algorithm to find smallest prime factor for all numbers from 1 to n.

algorithm to find smallest prime factor for all numbers from 1 to n

---

CPP/allfactors.cpp

I have added a C++ code for an algorithm to find all factors off a number.

algorithm to find all factors off a number

---

CPP/sieve

I have added a C++ code for sieve of erastosthenes.

sieve of erastosthenes

---

Python/generate_fib.py

This is a simple Fibonacci series generator program written in Python

A simple Fibonacci series generator
